### ISSUE TITLE
Improve handling of translations

### ISSUE THREAD

**Issue by KOIIIKE** [aritchie05/EcoCraftingTool#19]
Localization does not match with the in game spellings in Russian language

**Comment by aritchie05** [comment]
Need to redo the method for generating the locale-data.ts file. Maybe we can pull the information from Eco files somewhere? That would be a lot simpler and better than using Google Translate. If that's not possible, we need some kind of script that can read the items, recipes, skills etc. from the data files, call the Translate API, and generate the LocaleEntries.

One concern is avoiding overwriting locale data (in case there are manual fixes made to results from the API).

**Comment by CedricDx** [comment]
Hi, problem solved:
I got all the translations of the Eco game from "defaultstrings.csv" on https://fr.crowdin.com/project/eco-by-strange-loop-games, to put them in Update locale-data.ts.

Please validate it.

What is not translated on https://fr.crowdin.com/project/eco-by-strange-loop-games is therefore in English as in the game for more consistency.

Please remove the notion of google translation.

Send me a message when you have the version for Eco 9.6 so that I can redo the update, and the same for future versions...
