### ISSUE TITLE
Math is getting messed up at some point.

### ISSUE THREAD

**Issue by Jonixo** [aritchie05/EcoCraftingTool#28]
We first reazlied some mistake in Basic Circuits. Then I noticed Brick Fireplace, a much simpler craft.

Assuming clay cost is .25 and mortar is .3, iron bar is 1.75 with au4, my current setup.
A brick is .55 clay and 2.2 mortar = 0.79. tool says .73
A brick fireplace is 27.5 brick + 11 iron bar = assuming brick is .8, 41.25 total cost, tools says 71.44.

**Comment by Jonixo** [comment]
Found the issue, data is crawed from outdated wiki.

**Comment by aritchie05** [comment]
Looking into it

**Comment by aritchie05** [comment]
@Jonixo given your brick example, the correct price is actually calculated for the "Brick Recipe"

`(.55*.25) + (2.2*0.3) = 0.7975`

This is rounded to 0.8 because the display uses 2 decimal places.

However, there is another brick recipe, Shale Brick Recipe. Since you have a price of 0 for Crushed Shale, it is doing this calculation:

`((.55*.25) + (.55*0) + (4.4*0.3)) / 2 = 0.72875`

Note that everything is divided by 2 at the end because this recipe makes 2 bricks each. So the overall "Brick" price uses the cheapest recipe it can find, in this case the shale brick recipe. You can either remove the shale brick recipe or set a price for Crushed Shale to get a more accurate overall price. This cheaper Brick price of 0.73 is then used for the recipes that are dependent on Brick, for example Brick Fireplace.

![image](https://user-images.githubusercontent.com/15224019/142741512-7425cac9-6aa1-4d34-b262-7c5a0a348fe1.png)

**Comment by aritchie05** [comment]
As for the Brick Fireplace, it appears that it used to be crafted on a Masonry Table and was updated recently (maybe 9.4??)

Right now with the calculator, setting Masonry Table to BU4 will display the correct price for Brick Fireplace:

`(50 * 0.7975 * .55) + (20 * 1.75 * .55) = 41.18125 `

![image](https://user-images.githubusercontent.com/15224019/142741841-ad80b1a3-a793-4c8b-b065-fe724f657959.png)
