### ISSUE TITLE
Adding a specific recipe does not properly take into account existing output recipes

### ISSUE THREAD

**Issue by aritchie05** [aritchie05/EcoCraftingTool#3]
E.g.

1. Take logging, this populates hewn logs as an output
2. Add a carpentry recipe that uses hewn logs
3. Hewn logs will be added to ingredient list despite being in the outputs

**Comment by Tritoneko** [comment]
I feel like this thread is the best place for me to ask a question regarding the outputs and calculations for new products. 
Basically - I want to create a system or add the input of "hewn log*" so they are market price if you need to purchase the materials offhand. 
i.e. My wood purchasing price is 0.25 for "wood*" this makes 0.38 at 50% profit which is perfect.
But when you than go to see the lumber recipe it used wood* as it's natural input at 0.25 instead of 0.38.
I was wondering if there is any way to manually add additional inputs like a wood board or hewn log, or perhaps a tick box of something along the lines of "calculate recipes with stacking profit margin" if that makes sense?

Another example, if I have Oil drilling my costs would be super low, but if I want to buy on the market cause of time issues and someone is selling 1000 plastic and epoxy I'd rather be able to put those prices in the input to calculate my new pricing.

Hopefully this was clear enough, if not I would be happy to further work on this :)
